["Run name"]
name    = "16x8v1"

["Directories and Files"]
perambulator_dir    = "perambulator_dir"
perambulator_charm_dir    = "perambulator_dir"
mode_triplets_dir   = "mode_triplets_dir"
sparse_modes_dir    = "sparse_modes_dir"
tsrc_list   = ""
result_dir = "results"

["Geometry"]
N_t     = 16
N_k     = [8, 8, 8]

["Configurations"]
first   = 1
last    = 10
step    = 1

["Sources"]
N_src           = 2
src_separation  = 8

["Perambulator"]
label_light      = "perambulator_light_tsrc"
label_charm      = "perambulator_charm_tsrc"

["Baryon operators"]
Gamma = [["Pp", "C*G5"], ["Pp", "C*G5*Pp"]]
flavour = "uud" # "uds" or "uud"

["Momenta"]
p_sq = [0, 1]

["Correlator"]
method          = "full"  # "full" or "sparse"

["Various"]
continuation_run = false