["Run name"]
name    = "16x8v1"

["Directories and Files"]
perambulator_dir    = "perambulator_dir"
perambulator_charm_dir    = "perambulator_dir"
mode_doublets_dir   = "mode_doublets_dir"
sparse_modes_dir    = "sparse_modes_dir"
sparse_modes_dir_new = "sparse_modes_dir_new"   # only needed for modes_increase_separation.jl
tsrc_list   = ""
result_dir = "results"

["Geometry"]
N_t     = 16
N_k     = [8, 8, 8]

["Configurations"]
first   = 1
last    = 10
step    = 1

["Sources"]
N_src           = 2
src_separation  = 8

["Perambulator"]
label_light      = "perambulator_light_tsrc"
label_charm      = "perambulator_charm_tsrc"

["Momenta"]
p       = [[0, 0, 0],
           [1, 0, 0]]

["Correlator"]
method          = "full"  # "full" or "sparse"

["Increase Separation"]
N_sep_new       = 4

["Various"]
continuation_run = false