["Run name"]
name    = "16x8v1"

["Directories and Files"]
perambulator_dir    = "/home/stumpa/Seafile/Dokumente/HU_Berlin,DESY/Programs/wit_-_MainzLattice/wit-position_space_sampling/results_DStill/16x8_Nsep1/dat"
mode_doublets_dir   = "/home/stumpa/Seafile/Dokumente/HU_Berlin,DESY/Programs/wit_-_MainzLattice/wit-position_space_sampling/results_DStill/16x8_Nsep1/dat"
sparse_modes_dir    = "/home/stumpa/Seafile/Dokumente/HU_Berlin,DESY/Programs/wit_-_MainzLattice/wit-position_space_sampling/results_DStill/16x8_Nsep1/dat"
tsrc_list   = "/home/stumpa/Seafile/Dokumente/HU_Berlin,DESY/Programs/wit_-_MainzLattice/wit/results_DStill/16x8/dat/tsrc_list"
result_dir = "run_pseudoscalar/results"

["Geometry"]
N_t     = 16
N_k     = [8, 8, 8]

["Configurations"]
first   = 1
last    = 10
step    = 1

["Sources"]
N_src           = 2
src_separation  = 8

["Perambulator"]
label_base      = "light_tsrc"

["Momentum"]
p       = [1, 0, 0]