["Run name"]
name    = "16x8v1"

["Directories and Files"]
dat_dir     = "/home/stumpa/Seafile/Dokumente/HU_Berlin,DESY/Programs/wit_-_MainzLattice/wit/results_DStill/16x8/dat"
tsrc_list   = "/home/stumpa/Seafile/Dokumente/HU_Berlin,DESY/Programs/wit_-_MainzLattice/wit/results_DStill/16x8/dat/tsrc_list"
result_dir = "./"

["Configurations"]
first   = 1
last    = 10
step    = 1

["Sources"]
N_src           = 1
src_separation  = 1

["Perambulator"]
label_base      = "light_tsrc"

["Mode doublets"]
i_p     = 14        # [0, 0, 0]