["Run name"]
name    = "16x8v1"

["Directories and Files"]
perambulator_dir    = "perambulator_dir"
perambulator_charm_dir    = "perambulator_dir"
mode_doublets_dir   = "mode_doublets_dir"
tsrc_list   = ""
result_dir = "results"

["Geometry"]
N_t     = 16
N_k     = [8, 8, 8]
N_modes = "from perambulator" # "from perambulator" or Integer

["Correlator shape"]
direction       = "full"    # "forward", "backward", "forward/backward" or "full"
n_timeslices    = 8

["Configurations"]
first   = 1
last    = 10
step    = 1

["Sources"]
N_src           = 2
src_separation  = 8     # Integer or "file" if all src specified in tsrc_list

["Perambulator"]
label_light      = "perambulator_light_tsrc"
label_charm      = "perambulator_charm_tsrc"

["Momenta nonlocal"]
Ptot_sq      = [0]
p_sq_sum_max = [2]
chunk_size = "full" # Integer or "full"

["Momenta local"]
p       = "all"
#p       = [[0, 0, 0],
#           [1, 0, 0]]

["Various"]
continuation_run = false
